&ApplicationConfig

delay: &Delay
  min: 1200
  max: 3000

limit: &Limit
  count: 50000
  maxDepth: 10

page: &PageConfig
  landingPageName: 'landing page'
  pageNamePattern: 'page_${number}'

eventBus: &EventBus
  !!org.babich.crawler.metrics.EventBusWithMetricsExtension { mode : 'ASYNC' }

metrics: &Metrics
  registry: !!org.babich.crawler.metrics.InfluxRegistry { propertyFile : '/etc/app/influx.properties' }
#  registry: !!org.babich.crawler.metrics.InfluxRegistry { }

traverser:
  mode: BREADTH

backupService: &BackupService
  !!org.babich.crawler.interceptor.service.JdkSerializeBackupService { eventBus: *EventBus }

processing:
  defaultProcessing: !!org.babich.crawler.processing.DefaultJsoupPageProcessing { }
  processingList:

interceptorList:
  - *BackupService
  - &CircularLinksFilter !!org.babich.crawler.interceptor.filter.CircularLinksFilter { eventBus: *EventBus }
  - &SuccessorsMessageProducer !!org.babich.crawler.interceptor.SuccessorsMessageProducer { eventBus: *EventBus }
  - &SuccessorPagesPostProcessing !!org.babich.crawler.interceptor.service.SuccessorPagesPostProcessing { pageConfig: *PageConfig}
  - &PageSourceLocalPersister !!org.babich.crawler.interceptor.service.PageSourceLocalPersister { }
  - !!org.babich.crawler.interceptor.filter.MaximumDepthFilter { limit: *Limit, eventBus: *EventBus }
  - !!org.babich.crawler.interceptor.service.PageProcessingDelay { delay: *Delay }
  - !!org.babich.crawler.interceptor.service.PageSizeInitializer { }
  - !!org.babich.crawler.interceptor.service.PageUrlNormalizer { }
  - !!org.babich.crawler.metrics.PageMetricsInterceptor { }

eventListeners:
  - *BackupService
  - *CircularLinksFilter
  - *SuccessorsMessageProducer
  - *SuccessorPagesPostProcessing
  - *PageSourceLocalPersister
  - !!org.babich.crawler.metrics.MeterRegistryInitializer { config: *Metrics }
  - !!org.babich.crawler.metrics.PageMetricsProducer { }