version: '3.8'

services:
  web-crawler-app:
    image: ghcr.io/vadimbabich/web-crawler-test:latest
    environment:
      - APP_SLEEP=3
    command:
      [
        '-outputFile',
        '/var/app/data.txt',
        '-searchStr',
        'web+crawler',
        '-configPath',
        '/etc/app/custom-crawler-config.yml'
      ]
    volumes:
      - ./app/tmp:/tmp:rw
      - ./app/output:/var/app:rw
      - ./app/config:/etc/app:ro