version: '3.8'

services:
  influxdb:
    image: influxdb:2.1.1
    ports:
      - 127.0.0.1:8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=secureP@ssw0rd
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=micrometer
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Iou3WHVaKQdmVEsUtZniWMruRShepsJ7eZyN
      - INFLUXDB_DB=crawler
      - INFLUXDB_USER=readwrite-user
      - INFLUXDB_USER_PASSWORD=secureP@ssw0rd

  grafana:
    image: grafana/grafana:8.2.6
    depends_on:
      - influxdb
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - 127.0.0.1:3000:3000